# -*- coding: utf-8 -*-
"""Лаба 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zpAy63pfkI7AsMXWck2mKhC-_ZtA8Fny
"""

'''Самостоятельное задание'''
'1 задание'
a=5
b=int(input())
c=a*b
print(c)

'2 задание'
b=int(input())
a=int(input())
print((a+b)**2)

'3 задание'
b=10
a=15
c=int(input())
print((a+b)/c)

'4 задание (1 способ)'
b=int(input())
a=int(input())
c= (a**2) + (2*a*b) + (b**2)
print(c)

'4 задание (2 способ)'
b=int(input())
a=int(input())
print('(',a,'+',b,')','^ 2=',a,'^ 2 + 2 *',a,'*',b,'+',b,'^ 2=',2*a*b+b**2 )

'5 задание'
import math
b=int(input())
a=int(input())
c=int(input())
s=0
p=0
if (a+b)>c and (a+c)>b and (b+c)>a:
    p=(a+b+c)/2
    P=a+b+c
    s=math.sqrt(p*(p-a)*(p-b)*(p-c))
else:
    print('Такого треугольника не существует')
print('P=',P, 'S=',s)

'6 задание'
b=int(input())
a=int(input())
c=((a**3+14)/5)*b
print(c)

'7 задание'
b=int(input())
n=int(input())
c=(b**2)//n
print(c)

'8 задание'
'1 пункт'
a = float(input())
b = float(input())
if a % 1 != 0 and b % 1 != 0:
    print(int(a) // int(b))
else:
    print('Одно из чисел не дробное число')

'2 пункт'
a = int(input())
b = int(input())
if a>0 and b>0:
    print(a*b)

'3 пункт'
a = int(input())
b = int(input())
if a>0 and b>0:
    print(a%b)

'''Повышенный уровень'''
'1 задание'
n= float(input())
minyta=n/60
chas=minyta/60
den=chas/24
print('Секунд=',n,'Минут=',minyta,'Часов=',chas,'Дней=',den)

'2 задание'

n=int(input())
a=str(n)*2
b=str(n)*3
print(n+int(a)+int(b))

"""# Новый раздел"""



